name: Build Release Artifact

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - README

env:
  METABASE_VERSION: v0.50.13

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Metabase Repo
        uses: actions/checkout@v4
        with:
          repository: metabase/metabase
          ref: ${{ env.METABASE_VERSION }}

      - name: Checkout Driver Repo
        uses: actions/checkout@v4
        with:
          path: modules/drivers/rest

      - name: Install Clojure CLI
        run: |
          wget https://github.com/clojure/brew-install/releases/download/1.11.3.1463/linux-install.sh &&
          sudo bash ./linux-install.sh

      - name: Build REST driver
        run: |
          echo "{:deps {metabase/rest {:local/root \"rest\" }}}" > modules/drivers/deps.edn
          bin/build-driver.sh rest

      - name: Archive driver JAR
        uses: actions/upload-artifact@v4
        with:
          name: rest.metabase-driver.jar
          path: resources/modules/rest.metabase-driver.jar